// SPDX-License-Identifier: MIT
/**
 * RustChain Development Tools — Quick Actions
 *
 * Provides the "Claim Bounty" button that opens a PR template
 * with pre-filled content for submitting a bounty implementation.
 */

import * as vscode from "vscode";

const BOUNTY_PR_TEMPLATE = `## RustChain Bounty Implementation

### Bounty Reference
<!-- Fill in the bounty number and title -->
- Bounty #: 
- Bounty Title: 

### Summary
<!-- Briefly describe what you implemented -->

### Changes Made
<!-- List the files changed and what was done -->

### Testing
<!-- How did you test your implementation? -->

### Screenshots / Evidence
<!-- Add screenshots or output if applicable -->

### RTC Wallet for Reward
<!-- Your wallet name -->
Wallet: 

---
*Generated by RustChain VS Code Extension*
`;

export class QuickActionsProvider {
    constructor(private readonly context: vscode.ExtensionContext) {
        this.registerCommands();
    }

    private registerCommands(): void {
        this.context.subscriptions.push(
            vscode.commands.registerCommand("rustchain.claimBounty", async () => {
                const doc = await vscode.workspace.openTextDocument({
                    content: BOUNTY_PR_TEMPLATE,
                    language: "markdown",
                });
                await vscode.window.showTextDocument(doc, vscode.ViewColumn.One);
                vscode.window.showInformationMessage(
                    "Fill in the bounty details above and create your PR!",
                );
            }),
        );

        this.context.subscriptions.push(
            vscode.commands.registerCommand("rustchain.openBountyBrowser", async () => {
                const { BountyBrowserPanel } = await import("./bountyBrowser");
                new BountyBrowserPanel(this.context);
            }),
        );

        this.context.subscriptions.push(
            vscode.commands.registerCommand("rustchain.showEpochInfo", async () => {
                await vscode.commands.executeCommand("workbench.panel.markers.view.focus");
                const msg = "Open the Output panel to see epoch info, or use the status bar for quick view.";
                vscode.window.showInformationMessage(msg);
            }),
        );

        this.context.subscriptions.push(
            vscode.commands.registerCommand("rustchain.openMinerStatus", async () => {
                const config = vscode.workspace.getConfiguration("rustchain");
                const minerId = config.get<string>("minerId", "");
                if (!minerId) {
                    const set = "Set Miner ID";
                    const chosen = await vscode.window.showInformationMessage(
                        "No miner ID configured. Would you like to set one now?",
                        set,
                    );
                    if (chosen === set) {
                        await vscode.commands.executeCommand("rustchain.setMinerId");
                    }
                    return;
                }
                await vscode.commands.executeCommand("rustchain.checkNodeHealth");
            }),
        );
    }
}
