# ... existing code ...

def void_bridge_transfer(tx_hash):
    # ... existing code ...
    update_query = """
        UPDATE locks
        SET voided = True
        WHERE tx_hash = %s AND lock_type IN ('bridge_deposit', 'bridge_withdraw')
    """
    # ... existing code ...

# ... existing code ...