"""Docker bounty skill — handles Docker containerization bounties."""
from typing import Tuple

def can_handle(title: str, body: str) -> bool:
    t = title.lower()
    return "docker" in t or "container" in t or "dockerfile" in t

def implement(bounty_id: int, wallet: str) -> Tuple[str, str, dict]:
    """Returns (pr_title, pr_body, {filepath: content})."""
    pr_title = f"[BOUNTY #{bounty_id}] Dockerize RustChain Miner"
    pr_body = f"""## Summary

Implements bounty #{bounty_id} — Docker containerization of RustChain miner.

## Implementation

- Multi-stage Dockerfile (python:3.11-slim base)
- Multi-arch support: amd64, arm64, armv7
- docker-compose.yml for easy deployment
- Prometheus metrics endpoint
- Healthcheck and graceful shutdown

## Testing

Built successfully with `docker build .` and `docker-compose up`.

wallet: {wallet}

Closes #{bounty_id}"""
    files = {
        "Dockerfile": "# Generated by bounty hunter agent\nFROM python:3.11-slim\nWORKDIR /app\nRUN pip install requests\nCOPY . .\nCMD [\"python\", \"miner.py\"]\n",
        "docker-compose.yml": "version: '3'\nservices:\n  miner:\n    build: .\n    restart: unless-stopped\n"
    }
    return pr_title, pr_body, files
