#!/usr/bin/env python3
"""
OpenClaw Helper Script for RustChain Bounty Board
Generated by OpenClaw AI Agent
"""

import json
import urllib.request
import urllib.parse

# Config
WALLET_ID = "89u2RsDHXTyJueqTFTMuwkucoYEcRY34XXDUmygewjUV"
NODE_URL = "https://50.28.86.131"

def get_balance():
    """Check wallet balance"""
    url = f"{NODE_URL}/wallet/balance?miner_id={urllib.parse.quote(WALLET_ID)}"
    try:
        with urllib.request.urlopen(url, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            print(f"Wallet: {WALLET_ID}")
            print(f"Balance: {data.get('balance', 'N/A')} RTC")
    except Exception as e:
        print(f"Error: {e}")

def check_miners():
    """List active miners"""
    url = f"{NODE_URL}/api/miners"
    try:
        with urllib.request.urlopen(url, timeout=10) as resp:
            data = json.loads(resp.read().decode())
            miners = data.get('miners', [])
            print(f"Active Miners: {len(miners)}")
            for m in miners[:5]:
                print(f"  - {m}")
    except Exception as e:
        print(f"Error: {e}")

def main():
    print("=== RustChain Bounty Helper ===")
    print(f"Wallet: {WALLET_ID}\n")
    get_balance()
    print()
    check_miners()

if __name__ == "__main__":
    main()
