#!/usr/bin/env python3
"""
RustChain IBM 709 Miner - Host Attestation Submitter

This script reads attestation tapes generated by the IBM 709 miner
(simulated via SIMH) and submits them to the RustChain network.

Usage:
    python submit_host.py --tape attestation_output.tap --wallet WALLET.DAT

The IBM 709 (1958) has no networking capabilities, so attestations are
written to simulated 7-track tape and exported to a modern host for submission.
"""

import argparse
import json
import hashlib
import time
import struct
import sys
from pathlib import Path
from datetime import datetime

# RustChain node configuration
NODE_HOST = "50.28.86.131"
NODE_PORT = 8088
ATTEST_ENDPOINT = f"http://{NODE_HOST}:{NODE_PORT}/attest/submit"

# Dev fee configuration
DEV_FEE_WALLET = "founder_dev_fund"
DEV_FEE_AMOUNT = "0.001"

# IBM 709 word size
IBM709_WORD_BITS = 36
IBM709_WORD_BYTES = 5  # 36 bits = 4.5 bytes, we use 5 for alignment
IBM709_MAX_WORD = 0xFFFFFFFFF  # 36 bits all ones


def read_tape_file(tape_path: str) -> list:
    """
    Read SIMH tape image file.
    
    SIMH tape format:
    - Each record is preceded by a 2-byte length
    - Data follows in binary format
    - Records are separated by tape marks
    
    Returns list of 36-bit words.
    """
    words = []
    
    try:
        with open(tape_path, 'rb') as f:
            while True:
                # Read record marker
                marker = f.read(2)
                if not marker or len(marker) < 2:
                    break
                    
                # Check for tape mark (end of tape)
                if marker == b'\x00\x00':
                    break
                    
                # Read record length (in words)
                record_len = struct.unpack('>H', marker)[0]
                
                # Read record data
                for i in range(record_len):
                    word_data = f.read(5)  # 5 bytes per 36-bit word
                    if len(word_data) < 5:
                        break
                    
                    # Convert to 36-bit word (big-endian)
                    word = int.from_bytes(word_data, 'big') & IBM709_MAX_WORD
                    words.append(word)
                    
    except FileNotFoundError:
        print(f"Error: Tape file not found: {tape_path}")
        sys.exit(1)
    except Exception as e:
        print(f"Error reading tape: {e}")
        sys.exit(1)
    
    return words


def parse_attestation_record(words: list, offset: int) -> dict:
    """
    Parse a single attestation record from IBM 709 words.
    
    Record format:
    - Word 0: ATTEST_MARKER (octal 777777777777)
    - Word 1-3: Wallet ID
    - Word 4: Timestamp
    - Word 5-7: Attestation hash
    - Word 8: Checksum
    
    Returns dict with parsed fields or None if invalid.
    """
    if offset + 9 > len(words):
        return None
    
    marker = words[offset]
    expected_marker = 0o777777777777  # Octal marker from miner
    
    if marker != expected_marker:
        return None
    
    # Parse wallet ID (3 words = 108 bits)
    wallet_words = words[offset+1:offset+4]
    wallet_id = f"RTC{wallet_words[0]:012X}{wallet_words[1]:012X}{wallet_words[2]:012X}"[:43]
    
    # Parse timestamp
    timestamp = words[offset+4]
    
    # Parse attestation hash (3 words)
    hash_words = words[offset+5:offset+8]
    attestation_hash = f"{hash_words[0]:012X}{hash_words[1]:012X}{hash_words[2]:012X}"
    
    # Parse checksum
    checksum = words[offset+8]
    
    # Verify checksum
    expected_checksum = (hash_words[0] + hash_words[1] + hash_words[2]) & IBM709_MAX_WORD
    if checksum != expected_checksum:
        print(f"Warning: Checksum mismatch at offset {offset}")
    
    return {
        'wallet_id': wallet_id,
        'timestamp': timestamp,
        'attestation_hash': attestation_hash,
        'checksum_valid': checksum == expected_checksum
    }


def find_attestation_records(words: list) -> list:
    """
    Find all attestation records in tape data.
    
    Returns list of (offset, record_dict) tuples.
    """
    records = []
    marker = 0o777777777777
    
    offset = 0
    while offset < len(words):
        if words[offset] == marker:
            record = parse_attestation_record(words, offset)
            if record:
                records.append((offset, record))
                offset += 9  # Skip this record
            else:
                offset += 1
        else:
            offset += 1
    
    return records


def generate_miner_id(words: list) -> str:
    """
    Generate unique miner ID from initial entropy.
    """
    if len(words) < 3:
        return "IBM709-UNKNOWN"
    
    # Hash first few words to create miner ID
    entropy = f"{words[0]:012X}{words[1]:012X}{words[2]:012X}"
    hash_bytes = hashlib.sha256(entropy.encode()).digest()[:4]
    miner_id = f"IBM709-{hash_bytes.hex().upper()}"
    
    return miner_id


def create_attestation_json(record: dict, miner_id: str) -> dict:
    """
    Create JSON attestation payload for RustChain node.
    """
    return {
        "miner": record['wallet_id'],
        "miner_id": miner_id,
        "nonce": record['timestamp'],
        "device": {
            "arch": "ibm_709",
            "family": "vacuum_tube",
            "model": "IBM 709 (1958)",
            "word_size": 36,
            "memory_words": 32768,
            "technology": "vacuum_tube",
            "simulator": "SIMH IBM 7090",
            "emulated": True
        },
        "entropy": {
            "attestation_hash": record['attestation_hash'],
            "checksum_valid": record['checksum_valid']
        },
        "dev_fee": {
            "enabled": True,
            "wallet": DEV_FEE_WALLET,
            "amount": DEV_FEE_AMOUNT
        },
        "metadata": {
            "submission_time": int(time.time()),
            "submission_host": "modern_bridge",
            "original_arch": "IBM 709 (1958)"
        }
    }


def submit_attestation(attestation: dict) -> bool:
    """
    Submit attestation to RustChain node.
    
    Returns True on success, False on failure.
    """
    try:
        import requests
        
        response = requests.post(
            ATTEST_ENDPOINT,
            json=attestation,
            headers={"Content-Type": "application/json"},
            timeout=30
        )
        
        if response.status_code == 200:
            result = response.json()
            if result.get('success') or result.get('status') == 'ok':
                return True
        
        print(f"Node response: {response.status_code} - {response.text}")
        return False
        
    except requests.exceptions.RequestException as e:
        print(f"Network error: {e}")
        return False
    except Exception as e:
        print(f"Submission error: {e}")
        return False


def save_attestation_local(attestation: dict, output_dir: str):
    """
    Save attestation to local file (offline mode).
    """
    output_path = Path(output_dir) / f"attestation_{int(time.time())}.json"
    
    with open(output_path, 'w') as f:
        json.dump(attestation, f, indent=2)
    
    print(f"Saved attestation to: {output_path}")


def load_wallet(wallet_path: str) -> str:
    """
    Load wallet ID from wallet file.
    """
    try:
        with open(wallet_path, 'r') as f:
            wallet_id = f.read().strip()
            return wallet_id
    except FileNotFoundError:
        print(f"Warning: Wallet file not found: {wallet_path}")
        return None
    except Exception as e:
        print(f"Error loading wallet: {e}")
        return None


def main():
    parser = argparse.ArgumentParser(
        description='RustChain IBM 709 Miner - Host Attestation Submitter'
    )
    parser.add_argument(
        '--tape', '-t',
        required=True,
        help='Path to SIMH tape image file from IBM 709 miner'
    )
    parser.add_argument(
        '--wallet', '-w',
        help='Path to wallet file (optional)'
    )
    parser.add_argument(
        '--output', '-o',
        default='./attestations',
        help='Output directory for local attestations (default: ./attestations)'
    )
    parser.add_argument(
        '--offline',
        action='store_true',
        help='Offline mode - save attestations locally only'
    )
    parser.add_argument(
        '--verbose', '-v',
        action='store_true',
        help='Verbose output'
    )
    
    args = parser.parse_args()
    
    print("=" * 60)
    print("  RUSTCHAIN IBM 709 MINER - HOST SUBMITTER")
    print("  Bridging 1958 vacuum tube computing to 2026 blockchain")
    print("=" * 60)
    print()
    
    # Read tape file
    print(f"Reading tape file: {args.tape}")
    words = read_tape_file(args.tape)
    print(f"Read {len(words)} words from tape")
    print()
    
    if not words:
        print("No data found on tape!")
        sys.exit(1)
    
    # Find attestation records
    records = find_attestation_records(words)
    print(f"Found {len(records)} attestation record(s)")
    print()
    
    if not records:
        print("No valid attestation records found!")
        print("Make sure the IBM 709 miner has run and written attestations.")
        sys.exit(1)
    
    # Generate miner ID
    miner_id = generate_miner_id(words)
    print(f"Miner ID: {miner_id}")
    print()
    
    # Create output directory
    Path(args.output).mkdir(parents=True, exist_ok=True)
    
    # Process each attestation
    submitted = 0
    saved = 0
    
    for offset, record in records:
        print(f"Processing attestation at offset {offset}:")
        print(f"  Wallet: {record['wallet_id']}")
        print(f"  Timestamp: {record['timestamp']}")
        print(f"  Hash: {record['attestation_hash'][:32]}...")
        print(f"  Checksum: {'Valid' if record['checksum_valid'] else 'INVALID'}")
        
        # Create attestation JSON
        attestation = create_attestation_json(record, miner_id)
        
        if args.offline:
            # Offline mode - save only
            save_attestation_local(attestation, args.output)
            saved += 1
        else:
            # Try to submit to network
            print(f"  Submitting to RustChain node...")
            if submit_attestation(attestation):
                print(f"  ✓ SUCCESS! Attestation accepted")
                submitted += 1
            else:
                print(f"  ✗ Failed to submit, saving locally")
                save_attestation_local(attestation, args.output)
                saved += 1
        
        print()
    
    # Summary
    print("=" * 60)
    print("SUMMARY")
    print("=" * 60)
    print(f"Total attestations found: {len(records)}")
    print(f"Successfully submitted: {submitted}")
    print(f"Saved locally: {saved}")
    print()
    
    if submitted > 0:
        print("🎉 IBM 709 miner successfully submitted attestations!")
        print("   This is the oldest architecture mining RustChain!")
    elif saved > 0:
        print("📁 Attestations saved locally (offline mode or network error)")
        print("   Run with --offline to submit later")
    else:
        print("❌ No attestations were processed successfully")
        sys.exit(1)
    
    print()
    print("Antiquity Multiplier: 5.0x (LEGENDARY tier)")
    print("Architecture: IBM 709 (1958) - Vacuum Tube Era")
    print("=" * 60)


if __name__ == '__main__':
    main()
