name: RTC Reward Action

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]

jobs:
  rtc-reward:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: RTC Reward Action
        uses: ./.github/actions/rtc-reward-action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RTC_REWARD_WALLET: ${{ secrets.RTC_REWARD_WALLET }}
          RTC_REWARD_PK: ${{ secrets.RTC_REWARD_PK }}